# Generated by Django 2.2 on 2020-03-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://anvilhotel.com/wp-content/uploads/2017/08/food-placeholder.png', max_length=500),
        ),
    ]
