# Generated by Django 2.2 on 2020-03-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200323_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://anvilhotel.com/wp-content/uploads/2017/08/food-placeholder.png', max_length=500),
        ),
    ]
